name: DEV - Build Deploy API

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.*'

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build with dotnet
        run: dotnet build ./src/WebApi/WebApi.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish ./src/WebApi/WebApi.csproj -c Release -o ${{ github.workspace }}/webapi

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: artifact-api
          path: ${{ github.workspace }}/webapi

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    # environment:
    #   name: 'Development'
    #   url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: artifact-api
          path: ${{ github.workspace }}/webapi

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_DEV }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DEV}}
          package: ${{ github.workspace }}/webapi
