name: Development Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  ReactDir: ./WebApp/ClientApp/

jobs:
  build_react:
    name: Build React
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Make ENV file with variable substitution
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_GENERATE_SOURCEMAP: false
          envkey_APPENV: ${{ vars.APPENV_DEV }}
          envkey_APIURL: ${{ vars.APIURL_DEV }}
          envkey_APPURL: ${{ vars.APPURL_DEV }}
          envkey_AZURE_WEBAPI_NAME: ${{ vars.AZURE_WEBAPI_NAME }}
          directory: ${{env.ReactDir}}
          file_name: .env

      - name: "Echo file .env"
        run: cat ${{env.ReactDir}}/.env

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Yarn install
        working-directory: ${{env.ReactDir}}
        run: yarn install

      - name: Yarn build
        working-directory: ${{env.ReactDir}}
        run: yarn build:prod

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: webreact
          path: ${{env.ReactDir}}/build/

  deployment_react:
    name: Deployment React
    runs-on: ubuntu-latest
    needs: build_react

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: webreact
          path: ${{env.ReactDir}}/dist/

      - name: Deploy to Azure WebApp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_SB2 }}
          package: ${{env.ReactDir}}/dist/
