name: Development Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build_react:
    if: true
    name: Build React
    runs-on: ubuntu-latest

    env:
      ReactDir: ./WebApp/ClientApp/

    steps:
      - name: directory
        run: echo $ReactDir

      - uses: actions/checkout@v4

      - name: Make ENV file with variable substitution
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_GENERATE_SOURCEMAP: false
          envkey_APPENV: ${{ vars.APPENV_DEV }}
          envkey_APIURL: ${{ vars.APIURL_DEV }}
          envkey_APPURL: ${{ vars.APPURL_DEV }}
          envkey_AZURE_WEBAPI_NAME: ${{ vars.AZURE_WEBAPI_NAME }}
          directory: ./WebApp/ClientApp/
          file_name: .env

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Yarn install
        working-directory: ./WebApp/ClientApp/
        run: yarn install

      - name: Yarn build
        working-directory: ./WebApp/ClientApp/
        run: yarn build:prod

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: webreact
          path: ./WebApp/ClientApp/build/

  deployment_react:
    name: Deployment
    runs-on: ubuntu-latest
    needs: build_react

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: webreact
          path: ./WebApp/ClientApp/build/

      - name: Deploy to Azure WebApp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_SB2 }}
          package: ./WebApp/ClientApp/build/
