# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [staging]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Deploy to IIS Staging started
        run: |
          echo 'staging.${{ github.event.repository.name }}'
                            
      - name: IIS Stopped for ${{ github.event.repository.name }}
        run: |
          Import-Module WebAdministration
          Stop-WebSite 'staging.${{ github.event.repository.name }}'
          
      - name: Copy files into IIS
        run: |
          Copy-Item ./* C:/websites-wp/${{ github.event.repository.name }} -Recurse -Force 
                    
      - name: IIS Started for ${{ github.event.repository.name }}
        run: |
          Start-WebSite 'staging.${{ github.event.repository.name }}'
                    
      - name: Deployment Cleanup
        run: |
          Remove-Item ./* -Recurse -Force





# Runs a single command using the runners shell
#       - name: Run a one-line script
#         env:
#           REPOA: ${{ github.event.repository.name }}
#         # run: echo "$REPOA"
#         run: echo "environment=development" >> $REPOA
        
      # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
